
 ;block 2    opcodes 1

 db     "       ASSEMBLER CURRENT !  ASSEMBLER CONTEXT  !                     "
 db     "                         0x C3 0x 1 opcode ret                       "
 db     "                         0x CF 0x 1 opcode iretd                     "
 db     "                         0x F4 0x 1 opcode hlt                       "
 db     "                         0x FD 0x 1 opcode std                       "
 db     "                         0x FC 0x 1 opcode cld                       "
 db     "                         0x CE 0x 1 opcode into                      "
 db     "                         0x CC 0x 1 opcode int3                      "
 db     "                         0x EC 0x 1 opcode in_al,dx                  "
 db     "                         0x ED 0x 1 opcode in_eax,dx                 "
 db     "                         0x EE 0x 1 opcode out_dx,al                 "
 db     "                         0x EF 0x 1 opcode out_dx,eax                "
 db     "                         0x BA 0x 1 opcode mov_edx,#                 "
 db     "                         0x B8 0x 1 opcode mov_eax,#                 "
 db     "                         0x B9 0x 1 opcode mov_ecx,#                 "
 db     "                         0x BE 0x 1 opcode mov_esi,#                 "
 db     "                         0x BF 0x 1 opcode mov_edi,#                 "
 db     "                         0x 05 0x 1 opcode add_eax,#                 "
 db     "                         0x 0D 0x 1 opcode or_eax,#                  "
 db     "                         0x 25 0x 1 opcode and_eax,#                 "
 db     "                         0x 3D 0x 1 opcode cmp_eax,#                 "
 db     "                         0x A9 0x 1 opcode test_eax,#                "
 db     "                         0x B5 0x 1 opcode mov_ch,#                  "
 db     "                         0x A3 0x 1 opcode mov_[],eax                "
 db     "                         0x A1 0x 1 opcode mov_eax,[]                "
 db     "                         0x 40 0x 1 opcode inc_eax                   "
 db     "                         0x 43 0x 1 opcode inc_ebx                   "
 db     "                         0x 41 0x 1 opcode inc_ecx                   "
 db     "                         0x 46 0x 1 opcode inc_esi                   "
 db     "                         0x 47 0x 1 opcode inc_edi                   "
 db     "                         0x 48 0x 1 opcode dec_eax                   "
 db     "                         0x 49 0x 1 opcode dec_ecx                   "
 db     "                         0x 4D 0x 1 opcode dec_ebp                   "
 db     "                         0x 4F 0x 1 opcode dec_edi                   "
 db     "                         0x 58 0x 1 opcode pop_eax                   "
 db     "                         0x 5B 0x 1 opcode pop_ebx                   "
 db     "                         0x 59 0x 1 opcode pop_ecx                   "
 db     "                         0x 5D 0x 1 opcode pop_ebp                   "
 db     "                         0x 50 0x 1 opcode push_eax                  "
 db     "                         0x 53 0x 1 opcode push_ebx                  "
 db     "                         0x 51 0x 1 opcode push_ecx                  "
 db     "                         0x 55 0x 1 opcode push_ebp                  "
 db     "                         0x 60 0x 1 opcode pushad                    "
 db     "                         0x 61 0x 1 opcode popad                     "
 db     "                         0x 95 0x 1 opcode xchg_eax,ebp              "
 db     "                         0x 96 0x 1 opcode xchg_eax,esi              "
 db     "                         0x E9 0x 1 opcode jmp                       "

 db     " EXIT                                                                "

 db 0

db     0
 alignhe20
